### ISSUE TITLE
Multiselect and responsive bootstrap

### ISSUE THREAD

**Issue by everhardt** [t0m/select2-bootstrap-css#15]
This is the best solution for implementing select2 in bootstrap I've seen until now! 

Unfortunately it doesn't allow yet for the responsive functionality of Bootstrap. Would it be possible to add that, so that when screen-width is max. 767px, the multiselect container gets a 100% width?

**Comment by afattahi54** [comment]
+0

**Comment by EduVillas** [comment]
+0

**Comment by skabbit** [comment]
+1

**Comment by t0m** [comment]
Closing out - this has probably been taken care of here:

https://github.com/select2/select2-bootstrap-theme
