### ISSUE TITLE
Select2 not respecting parent width.

### ISSUE THREAD

**Issue by triqi** [t0m/select2-bootstrap-css#42]
**Problem:** When you select an option that is larger than the Select2, the control would expand itself to fit the newly selected option, even if it means exceeding the width of the parent container.

**Expected outcome:** If the selected option is large, then the text content should become clipped and text ellipsis should be visible.

You can see this in the demonstration website if you manually adjust any of the Select2 controls width to an arbitrary small value and then proceed to selecting any options.

**Comment by guerler** [comment]
It seems to work if the select2 field is wrapped in a table with a fixed table-layout. http://jsfiddle.net/guerler/oqggpsaw/

**Comment by NyroTheCat** [comment]
Thanks!

**Comment by yn-coder** [comment]
I use the pinax, bootstrap-form, and I set the 
`SELECT2_BOOTSTRAP = True`

**Comment by dickieirwin** [comment]
+1

**Comment by la0rg** [comment]
fixed table-layout is working fine

**Comment by ageorgousakis** [comment]
+1

**Comment by conmute** [comment]
I solved for `.input-group` by doing this:


    // fix .input-group width issue
    .select2-container--default .select2-search--inline .select2-search__field {
        width: auto !important;
    }

**Comment by fk** [comment]
Thanks to all of you providing fixes for/insight on this; I'm glad to say that I finally found the time to look into this and things are looking good – at least in latest Chrome, Firefox and Safari. I can't test the IE's right now because my IE VM's collectively decided to stop working (and my current bandwidth is limited so I can't download fresh images right now).

The fix _for now_ employs `display:table` and `table-layout:fixed` like suggested by @guerler, @la0rg and finally @ryanbeymer [here](https://github.com/fk/select2-bootstrap-theme/issues/2#issuecomment-89918359) and is in for both Select2 v3 [here](https://github.com/fk/select2-bootstrap-css/commit/03302f11c67b7cb65a5902b7a7bb2f1eabdcd6df) and for the new Select2 v4 theme [over there](https://github.com/fk/select2-bootstrap-theme/commit/27be80937967b0d667d8ca21a4b44b6f3b5d983a) (plus a fix [here](https://github.com/fk/select2-bootstrap-theme/commit/1beb7697fb0a59682064de14b0d97cf273beb862)).
Please be aware that the fix has not yet landed in the `bootstrap3` branch at https://github.com/t0m/select2-bootstrap-css/ but is only available in [my fork](https://github.com/fk/select2-bootstrap-css/tree/bootstrap3) for now. You won't find the fix on the [demos for the latter](https://fk.github.io/select2-bootstrap-css/), but it's live for the [demos for the Select2 v4 theme](http://fk.github.io/select2-bootstrap-theme/). 

"for now" because as previously mentioned I'm not able to test IE's – that's exactly the reason why there's no release yet. I also haven't been looking into what @raulromanp suggested [earlier](https://github.com/t0m/select2-bootstrap-css/issues/42#issuecomment-57695308), plus I'd to discuss what @conmute suggested: 

@conmute That makes sense. Did you see https://github.com/fk/select2-bootstrap-theme/issues/2? There's a lot of noise in the discussion (thanks to me :-/) – sorry for that – the interesting part is [here](https://github.com/fk/select2-bootstrap-theme/issues/2#issuecomment-90070141), where at the end of his comment @kevin-brown mentions that `resizeSelect` isn't triggered when the browser window is resized. @conmute If your fix works, wouldn't it mean that the input for the Multi Select2's wouldn't need a width set via an inline style _at all_? (CC @kevin-brown – I guess there _is_ a reason for the explicit setting of a width?) Also, on what browsers did you test?

**Comment by ChaIcuWo** [comment]
So I have what I think is a similar problem, but a different solution.

There were two problems: 1. the same width of the `.select2-container` span that others have talked about was being rendered at 100px; and 2. even when the main input's width was fixed via css, the `.searchselect2-search__field` input stayed very small.

My problem was only happening on a multiple select input which is loaded within a hidden div (`display: none`), but is eventually displayed. I updated my css to the v3 file linked to above, however this alone didn't solve my problem. My solution was:

1. add `style="width:100%"` to my original input tag.
2. to fix the size of the search field after an initial selection had been made I did the following jQuery:
```
$("span.select2-selection--multiple").on("mouseover",function(){
		$("li.select2-search--inline").each(function() {
			$(this).find("input").css("width", "100%");
        });
});
```

**Comment by xumix** [comment]
No news here?

**Comment by aeksco** [comment]
@guerler Nice tip wrapping the ```<select>``` element with a table! With ```border: 0``` CSS it's indistinguishable from the standard implementation.

The following markup works nicely for me in ```Bootstrap v4.0.0-alpha.2```:

```jade
table( style="width: 100%; border: 0; table-layout: fixed !important;" )
  tr
    td
      select.form-control.c-select( name='tags' multiple='true' )
```

**Screenshot:**
<img width="695" alt="screenshot 2016-02-07 13 26 15" src="https://cloud.githubusercontent.com/assets/4616233/12874271/965fc5fa-cd9e-11e5-82b9-4f74658bf361.png">

**Comment by diegys** [comment]
`  Select2.prototype._resolveWidth = function ($element, method) {
    var WIDTH = /^width:(([-+]?([0-9]*\.)?[0-9]+)(px|em|ex|%|in|cm|mm|pt|pc))/i;

    if (method == 'resolve') {
      var styleWidth = this._resolveWidth($element, 'style');

      if (styleWidth != null) {
        return styleWidth;
      }

      return this._resolveWidth($element, 'element');
    }

    if (method == 'element') {
      var elementWidth = $element[0].innerWidth;

      if (elementWidth <= 0) {
        return 'auto';
      }

      return elementWidth + 'px';
    }

    if (method == 'style') {
      var style = $element.attr('style');

      if (typeof(style) !== 'string') {
        return null;
      }

      var attrs = style.split(';');

      for (var i = 0, l = attrs.length; i < l; i = i + 1) {
        var attr = attrs[i].replace(/\s/g, '');
        var matches = attr.match(WIDTH);

        if (matches !== null && matches.length >= 1) {
          return matches[1];
        }
      }

      return null;
    }

    return method;
  };`

I just replaced `var elementWidth = $element.outerWidth(false);` with `var elementWidth = $element[0].innerWidth;` and it works.

**Comment by koolhuman** [comment]
@diegys I tried your ur solution by changing the the line you suggested directly in select2.js file but its not working for mozilla

**Comment by diegys** [comment]
@koolhuman Well, display table doesn't work for my layout.
You should also replace `display: inline-block` with `display: block` for `.select2-container`  and remove width:100% !Important.

**Comment by mprandot** [comment]
Work to me adding width style in select input :
Ex:

```
<div style=" width : 350px; ">
     <select  style="width : 100%;" class="select2" >
      ...
      ...
     </select>
</div>
```

**Comment by cabloo** [comment]
I had to use this CSS:

``` css
.ui-select-match-text, .ui-select-choices-row-inner {
  max-width: 100%;
  text-overflow: ellipsis;
  overflow: hidden;
}
```

with [this fiddle](http://jsfiddle.net/guerler/oqggpsaw/)

**Comment by ksuhiyp** [comment]
display:table !important; table-layout:fixed !important worked for me in the inspector but not working when adding them to input-group selector in the CSS file with important pri

@fk @guerler @la0rg Can you please advice which selector should i use to get the effects?

**Comment by MichaelRise** [comment]
Hey,

I use this solution - Example:

    // Fix select2 width
    $(window).on('resize', function() {
    	$('.form-group').each(function() {
    		var formGroup = $(this),
    			formgroupWidth = formGroup.outerWidth();
    		
    		formGroup.find('.select2-container').css('width', formgroupWidth);
    		
    	});
    });

Live - [https://jsfiddle.net/Lwy6qnwy/][1]


  [1]: https://jsfiddle.net/Lwy6qnwy/

**Comment by krzysobo** [comment]
Clearing the "style" attribute of each element having the ".select2-search__field" class  programatically with jQuery helps:

`$(".select2-search__field").attr('style', "");`

**Comment by Cristallix** [comment]
@MichaelRise I don't like to use JS but your solution works perfectly. Thank you a lot.

**Comment by ToreOlavKristiansen** [comment]
I reverted back to the standard select2 display style and added a next-sibling style to fix the issue for form-control classed select2.
```
.select2-container--bootstrap {
  display: inline-block;
}

select.form-control + span.select2-container--bootstrap {
  display: block;
  width: 100% !important;
}
```

**Comment by mprandot** [comment]
$('.select').select2({width: "100%"}) works fine.

**Comment by santaclaus21** [comment]
@mprandot it's complete not working for me.
@diegys - your code is working great!

.select2-container--default {
display: table!important;
table-layout: fixed!important;
}

**Comment by ToreOlavKristiansen** [comment]
This does not work for the bootstrap theme, modifying the class name to .select2-container--bootstrap. Adding width: "100%" to select2 options works fine.

**Comment by waqasraza123** [comment]
I fixed it by adding 
```.select2-container {
    width: 100% !important;
}```

**Comment by trheyi** [comment]
add table frame , before select2 init 
```javascript
jQuery('.js-select2').each( function( index, item ) {

            if ( $(this).parent().hasClass("input-group")  ) {
                var parent = $(this).parent();
                var $frame =  
                    $('<table style="border:#fff solid 0px; width:100%; table-layout: fixed !important;">' +
                        '<tr><td>'+
                        '</td></tr>' +
                    '</table>');

                var $td = $('td', $frame );
                    $td.append($(this));
                    parent.append($frame);
            }

           jQuery(item).select2( option );
}
```

**Comment by JohannWNel** [comment]
This is my solution to the problem: as the above mentioned worked but had to also size the contents.

```less
    .select2-container {
        display: table!important;
        table-layout: fixed!important;
        .selection {
            height: 100%;
            float: left;
            width: 100%;
        }
    }
```

**Comment by opctim** [comment]
Hi guys. I had the same problem. 

My HTML structure looks like this:

```html
<div class="row">
    <div class="col-md-4">
        <div class="input-group">
            <div class="input-group-addon">Name</div>
            <input type="text" name="name" class="form-control" autocomplete="off" required>
        </div>
    </div>
</div>
```

The select2 was 15px too wide, which is the horizontal padding of the Bootstrap column.

To fix this, I wrote this code:

```javascript
$(document).ready(function(){
    $(".input-group .select2.select2-container").each(function(){
        var bootstrapColumn = $(this).parent(".input-group").parent();
        var padding = (bootstrapColumn.innerWidth() - bootstrapColumn.width()) / 2;

        $(this).css({
            width: ($(this).width() - padding) + "px"
        });
    });
});
```

I hope I this helps.

**Comment by Michael-M-Judd** [comment]
None of the above fixes worked for me, however adding a simple `<form></form>` around my select element managed to fix this problem.

**Comment by petedegraw** [comment]
Another option is to check for the element with width set to say "100px", then target that with width: auto. In my case, using Rails, Select2, with Bootstrap...

```
span.select2.select2-container.select2-container--bootstrap {
  width: auto !important;
}
```

**Comment by shirazi18** [comment]
```
.input-group .select2-container, .form-group .select2-container {
  position: relative !important;
  z-index: 2;
  float: left !important;
  width: 100% !important;
  margin-bottom: 0 !important;
  display: table !important;
  table-layout: fixed !important;
}
```

**Comment by triqi** [comment]
I'm closing this issue as this repo is now marked as deprecated. See official repo here - https://github.com/select2/select2-bootstrap-theme
