### ISSUE TITLE
Please upload to cdnjs.com

### ISSUE THREAD

**Issue by comerc** [t0m/select2-bootstrap-css#61]

**Comment by fk** [comment]
I assume this is about the version for Bootstrap 3?

**Comment by fk** [comment]
[Submitted](https://github.com/cdnjs/cdnjs/pull/4309)! :)

**Comment by fk** [comment]
The files do not show up in the search results on the [cdnjs homepage](https://cdnjs.com/) yet, but you can now grab the Bootstrap 3 version here:

 * https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-css/1.4.6/select2-bootstrap.min.css
 * https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-css/1.4.6/select2-bootstrap.css
