### ISSUE TITLE
404 on demo page

### ISSUE THREAD

**Issue by oguimbal** [t0m/select2-bootstrap-css#71]
Hello,

Just to notify you: http://t0m.github.io/select2-bootstrap-css/  i got 404s for select2.js & css

**Comment by fk** [comment]
Damn – I keep forgetting about the Bootstrap 2 version; should have fixed this when taking care of #64.
At it!

**Comment by fk** [comment]
Fixed; thanks for the heads up @oguimbal!
:+1:
