### ISSUE TITLE
Undefined variable $baseLineHeight

### ISSUE THREAD

**Issue by brunowego** [t0m/select2-bootstrap-css#75]
On `select2-bootstrap.scss` file, I get undefined variable $baseLineHeight.

**Comment by brunowego** [comment]
For bootstrap 3, the default value variable name is `$line-height-base`.

**Comment by fk** [comment]
Bruno, please check out the [`bootstrap3`](https://github.com/t0m/select2-bootstrap-css/tree/bootstrap3) branch – it contains a version for … guess what, Bootstrap 3 ;-) (while `master` contains the initial version by @t0m targetting Bootstrap 2) and should resolve your issue.

I'll do my best to update the readme in `master` to avoid this kind of confusion in the future.

**Comment by fk** [comment]
Updated readme in https://github.com/t0m/select2-bootstrap-css/commit/416aed798ff015d1f7d3b3fe76add6dddf48b0ef.
