### ISSUE TITLE
Styles not applied

### ISSUE THREAD

**Issue by afilina** [t0m/select2-bootstrap-css#82]
I added the css to my page in that order:
bootstrap.css
select2.css
select2-bootstrap.css

I followed the examples exactly as on the demo page: `<select class="select2 form-control">` I'm calling `$(".select2").select2()` without any options. It still displays the default select2 styles.

**Comment by fk** [comment]
Hello @afilina, sorry for coming back so late.

Are you adressing the select2-boostrap-css version for Bootstrap 2 (in the `master` branch) or the Bootstrap 3 version in the [`bootstrap3`](https://github.com/t0m/select2-bootstrap-css/tree/bootstrap3) branch?

Would you be so kind to provide a JSFiddle or similar to demonstrate your setup?
Thank you!

**Comment by hassan1709** [comment]
If someone else find this issue and has not solved it yet, [check this out](http://stackoverflow.com/questions/33422127/how-to-use-select2-with-meteor)
