### ISSUE TITLE
set "height: 38px;     line-height: 1.82857;"  for default

### ISSUE THREAD

**Issue by yuomtheara** [t0m/select2-bootstrap-css#83]
the select2 height  is smaller than default of bs3
when i set
```
.select2-container .select2-choice {
    height: 38px;
    line-height: 1.82857;
}
```
It is OK.

**Comment by fk** [comment]
For me, doing what you suggest results in the Select2 widget being 4px too high:

![height-38px](https://cloud.githubusercontent.com/assets/21834/7029470/3e210f10-dd5e-11e4-8967-242c841d6259.png)

Is this adressing the select2-boostrap-css version for Bootstrap 2 (in the `master` branch) or the Bootstrap 3 version in the [`bootstrap3`](https://github.com/t0m/select2-bootstrap-css/tree/bootstrap3) branch? If the latter is the case, do the [demos](https://fk.github.io/select2-bootstrap-css/) work for you?

Please clarify your problem and if possible provide a JSFiddle or similar to demonstrate your problem.
Thank you!

**Comment by yuomtheara** [comment]
Maybe, I use bootswatch style override.

**Comment by fk** [comment]
@yuomtheara Thanks for clarifying!

While I'm not familiar with https://bootswatch.com/ – which is what I assume you're referring to – I saw this

> Changes are contained in just two LESS or SASS files, enabling modification and ensuring forward compatibility.

on their homepage; this leads me to think that you must be compiling your own version of Bootstrap's CSS?

Well, the cool thing about select2-bootstrap-css is that it actually uses Bootstrap's variables and mixins to build the CSS which integrates Select2 with Bootstrap – Bootstrap's variables and mixins are imported in https://github.com/t0m/select2-bootstrap-css/blob/master/lib/build.scss or https://github.com/t0m/select2-bootstrap-css/blob/master/lib/build.less and then used in https://github.com/t0m/select2-bootstrap-css/blob/master/lib/select2-bootstrap.scss and https://github.com/t0m/select2-bootstrap-css/blob/master/lib/select2-bootstrap.less.

Try to reference your version of Bootstrap and the variables/mixins which are most likely overridden in the "two LESS or SASS files" in the `build.*` files I mentioned above, and then compile them to build your own version of select2-bootstrap-css.
