### ISSUE TITLE
missing copyright statement in `select2-bootstrap.css`

### ISSUE THREAD

**Issue by onlyjob** [t0m/select2-bootstrap-css#85]
Please add copyright statement to `select2-bootstrap.css`. Thanks.

**Comment by t0m** [comment]
Hi this should be covered in the official repo:

https://github.com/select2/select2-bootstrap-theme

Thanks!

**Comment by onlyjob** [comment]
Thanks, reported as https://github.com/select2/select2-bootstrap-theme/issues/43
