### ISSUE TITLE
Any plans on adding support for v4.0 of select2?

### ISSUE THREAD

**Issue by mrchief** [t0m/select2-bootstrap-css#86]
First of all, thanks for putting this up! Great effort!

I tried using this with v4.0.0-rc.2 and it seems that the markup as well as classes differ significantly. I know its still in RC but do you have any plans or have you started adding support for v4?

**Comment by fk** [comment]
Hi there @mrchief! There is a version for Select2 v4; [quoting myself](https://github.com/t0m/select2-bootstrap-css/issues/63#issuecomment-88724036):

> I just pushed my work to [a new repository](https://github.com/fk/select2-bootstrap-theme) to avoid handling another version in here.
> Demos are up at http://fk.github.io/select2-bootstrap-theme/.

**Comment by mrchief** [comment]
Cool! Thanks! I remember seeing that link somewhere but guess it got buried in Google results.
