### ISSUE TITLE
Undefined Error

### ISSUE THREAD

**Issue by attiqeurrehman** [t0m/select2-bootstrap-css#88]
Hi,

I am getting the following error:

![capture](https://cloud.githubusercontent.com/assets/1382615/7582354/0b0d89c4-f8a6-11e4-8cc0-85ca15083715.PNG)

Here's my code:

$('.select2').select2();

Thanks,
Attiqe

**Comment by fk** [comment]
Hi @attiqeurrehman! I believe the [home of the Select2 plugin](https://github.com/ivaynberg/select2) is the appropriate place to ask your question.

This project – select2-bootstrap-css – merely offers "simple CSS to make Select2 widgets fit in with Twitter Bootstrap" and thus does not deal with implementation issues regarding Select2.

**Comment by fk** [comment]
I see you already have done so with https://github.com/select2/select2/issues/3451.
Please follow the advice given there.
