### ISSUE TITLE
Select2 is being truncated when not focused 

### ISSUE THREAD

**Issue by parthsha** [t0m/select2-bootstrap-css#89]
Hi, I am trying to use a select2 in a bootstrap modal and I am experiencing issues with the way select2 is rendering at the moment when I am not interacting with it. When I do interact with it, it renders and works properly. I am hoping someone could guide me on how to solve this issue. I have created a jsfiddle to demonstrate what is happening at the moment.

https://jsfiddle.net/parthsha/aabq9utc/

**Comment by parthsha** [comment]
Hi, I did more investigation on this issue and discovered it is only happening in Chrome v 43.0.2357.81 for me. When I open the same page in IE v11.0.9600.17801 or Firefox v38.0.1 then this issue isn't happening at all. 

I have also noticed that if I were to change the max-width of my parent form-group to an odd number, then this issue doesn't happen anymore.

Should I conclude this as a Chrome bug or is there any alternate fix I should be going for? I really don't like the idea of artificially fixing the parent max-width to an odd number!

**Comment by trunda** [comment]
:+1: same problem here.

**Comment by t0m** [comment]
I think this has been fixed now, I took a look and it doesn't seem to appear anymore on chrome 50.0.2661.102. If it's still happening please report an issue on the official repo here: 

https://github.com/select2/select2-bootstrap-theme

Thanks!
