### ISSUE TITLE
Bootstrap3 branch through composer

### ISSUE THREAD

**Issue by SilverFire** [t0m/select2-bootstrap-css#90]
Hello, guys!
Have a huge problem with getting your repo through composer-npm.

I have a root repo, which requires repo A, which requires your asset from bootstrap3 branch.

Root repo: 

```json
        "require": {
              "myvendor/repoA": "~1.0"
        }
```

Repo A:

```json
        "require": {
              "otherVendor/otherRepo": "~2.4",
              "npm-asset/select2-bootstrap-css": "dev-bootstrap3"
        }
```

The root repo `minimum-stability` is set to `stable`, but using require of your repo, causes to drop minimum-stability to `dev`, or to whitelist your repo in the root package with the `@dev` stability flag. This really makes my ass hurt. :unamused: 

Here is a good article about stability flags, which will help you to understand, what am I talking about: https://igor.io/2013/02/07/composer-stability-flags.html

Could you, please, create a subrepo for this branch in your vendor?  Here is a manual about submodules in git: http://git-scm.com/docs/git-submodule

Thank you!

**Comment by sol-hiqdev** [comment]
:+1:

**Comment by Besedin86** [comment]
+1

**Comment by t0m** [comment]
Closing this out, the official plugin should have everything in a stable condition:

https://github.com/select2/select2-bootstrap-theme

Thanks!
