### ISSUE TITLE
ES2015 modules support

### ISSUE THREAD

**Issue by cAhmad** [t0m/select2-bootstrap-css#93]
Hi,

Firstable, thanks for your works, we really enjoy it.
We are migrating to ES2015 modules, we found that the css file has not enough weight to override select2.css.

Is there any plan to make your css ES2015 modules compatible?

**Comment by t0m** [comment]
Hi, check out the official repo here (if you haven't already):

https://github.com/select2/select2-bootstrap-theme

Thanks!
