### ISSUE TITLE
Select2 for Bootstrap 4

### ISSUE THREAD

**Issue by shoudaos** [t0m/select2-bootstrap-css#95]
Hello.
How soon do you begin to develop your lib for bootstrap 4?

**Comment by pruhstal** [comment]
+1

**Comment by phazei** [comment]
:+1: 
https://github.com/t0m/select2-bootstrap-css/issues/63

**Comment by asisti2-pruebas** [comment]
+1

**Comment by sdaitzman** [comment]
:+1:

**Comment by darkwinternight** [comment]
👍

**Comment by ryanannatuvasquez** [comment]
👍

**Comment by t0m** [comment]
Hey everyone, check out my comment here: https://github.com/t0m/select2-bootstrap-css/issues/63#issuecomment-222211631

Ina nutshell, the code has been moved into the select2 repo so all feature requests should go here: https://github.com/select2/select2-bootstrap-theme

Thanks!
