### ISSUE TITLE
why is it so slow?

### ISSUE THREAD

**Issue by gbaumgart** [t0m/select2-bootstrap-css#96]
Hi,
probably an edge case but when creating around 40 select boxes, it almost last 4-5 secs. Do you know what cause it being that slow? I use minimal to no extra features (search,..)
g

**Comment by cyberbit** [comment]
Is it slow without using the extra styles, or with? Or both?

**Comment by gbaumgart** [comment]
nothing extra, all on default. But i figured why: the refresh method seems to take overly long and I got around calling it. thanks, gonna close it.
