### ISSUE TITLE
Release Numbering

### ISSUE THREAD

**Issue by robertmain** [t0m/select2-bootstrap-css#98]
There is something odd going on with the release numbering. It jumps from 1.4.x to 1.2.x - what's up with this?

![image](https://cloud.githubusercontent.com/assets/537684/17889701/77684e0c-6929-11e6-876c-a639ca091e02.png)

**Comment by t0m** [comment]
Hi Robert, one of the releases is on the bootstrap2 (master) branch and the other is on the bootstrap3 branch. I'd like to remove it since the newer versions of the bootstrap3 code are in a different repo, but I'm worried people might be using it.

**Comment by robertmain** [comment]
Ah right - that kinda makes sense. It just threw me for a second :)
