### ISSUE TITLE
Not compatible with bootstrap 4 -

### ISSUE THREAD

**Issue by kamranbashir** [t0m/select2-bootstrap-css#99]
The dropdown does not work in bootstrap 4

**Comment by fk** [comment]
Hi @kamranbashir! I added the Bootstrap 3/Select2 v3 version of this project, located in the [`bootstrap3` branch](https://github.com/t0m/select2-bootstrap-css/tree/bootstrap3), and also maintained this project for a little while. If you need an (unmaintained) Select2 v3 integration for Bootstrap 2 or 3, you are in the right place.

If you are using Select2 v4, you can find a similar integration for Bootstrap 3 at [https://github.com/select2/select2-bootstrap-theme](https://github.com/select2/select2-bootstrap-theme). Select2 v4 added theming capabilities, I adjusted the original select2-bootstrap-css to work with v4, and the Select2 organization officially adopted the theme.

Unfortunately, [https://github.com/select2/select2-bootstrap-theme](https://github.com/select2/select2-bootstrap-theme) is not yet ready for Bootstrap 4, but if you are not afraid of compiling the CSS yourself, you can take a look at https://github.com/select2/select2-bootstrap-theme/issues/60 where the users of the theme came up with some workarounds for Bootstrap 4.
